#!/usr/bin/env python3
import sys
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = TESTS_DIR.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(TESTS_DIR))

from html_report import build_html_report
from test_report import sample_model


class HtmlReportTests(unittest.TestCase):
    def test_html_is_self_contained_and_has_all_major_sections(self):
        rendered = build_html_report(sample_model())

        self.assertTrue(rendered.startswith("<!-- Generated by Codex html-report -->"))
        self.assertIn("GitHub 开源趋势与项目复用雷达", rendered)
        for section_id in (
            "overview", "rankings", "categories", "reuse", "featured",
            "history", "market", "watchlist", "quality",
        ):
            self.assertIn(f'id="{section_id}"', rendered)
        self.assertIn("org/reusable", rendered)
        self.assertNotIn("https://cdn", rendered)
        self.assertNotIn("TODO", rendered)

    def test_growth_rankings_include_current_total_and_growth_columns(self):
        model = sample_model()
        model["rankings"]["daily"][0]["total_stars"] = 2000
        model["rankings"]["daily"][0]["value"] = 6
        model["rankings"]["weekly"][0]["total_stars"] = None
        model["rankings"]["weekly"][0]["value"] = 69

        rendered = build_html_report(model)

        self.assertIn(
            "<th>当前累计 Star</th><th>24h 新增 Star</th>",
            rendered,
        )
        self.assertIn(
            "<th>当前累计 Star</th><th>7d 新增 Star</th>",
            rendered,
        )
        self.assertIn("<td>2,000</td><td>+", rendered)
        self.assertIn("<td>缺失</td><td>+", rendered)

    def test_source_statuses_are_chinese_and_score_badge_is_centered(self):
        model = sample_model()
        model["metadata"]["source_status"] = [
            {"source": "github_top", "status": "ok"},
            {"source": "github_details", "status": "degraded"},
            {"source": "github_star_fallback", "status": "partial"},
        ]

        rendered = build_html_report(model)

        self.assertIn("GitHub 总 Star 榜", rendered)
        self.assertIn("GitHub 仓库详情", rendered)
        self.assertIn("累计 Star 兜底", rendered)
        self.assertIn('class="status ok">正常</strong>', rendered)
        self.assertIn('class="status degraded">不可用</strong>', rendered)
        self.assertIn('class="status partial">部分可用</strong>', rendered)
        self.assertIn("display:inline-flex", rendered)
        self.assertIn("align-items:center;justify-content:center", rendered)
        self.assertIn("height:36px", rendered)

    def test_market_evidence_uses_chinese_labels(self):
        model = sample_model()
        model["market_trends"][0]["evidence"] = [{
            "type": "ranking_data",
            "source": "local history 7d",
            "period": "7d",
            "metric": "weekly_growth",
            "value": 1234,
            "status": "ok",
        }]

        rendered = build_html_report(model)

        self.assertIn("<th>数据证据</th>", rendered)
        self.assertIn("类型：榜单数据", rendered)
        self.assertIn("来源：本地历史快照（过去7天）", rendered)
        self.assertIn("周期：过去7天", rendered)
        self.assertIn(
            "指标：7日新增 Star；数值：1,234；状态：正常",
            rendered,
        )
        self.assertNotIn("type：", rendered)

    def test_quality_section_uses_chinese_labels(self):
        rendered = build_html_report(sample_model())

        self.assertIn("来源状态", rendered)
        self.assertIn("来源：GitHub API；状态：正常", rendered)
        self.assertNotIn("source_status", rendered)


if __name__ == "__main__":
    unittest.main()
